### ISSUE TITLE
A/B testing

### ISSUE THREAD

**Issue by migo315** [bestit/feature-toggle-bundle#11]
A BucketTestStash for A/B testings.

**Comment by migo315** [comment]
Instead of a new Stash ... let's merge it to config. Example:

```
best_it_feature_toggle:
    features:      
        feature_123:
            active: true
            
        feature_abc:
            percentage:
               percentage: 50 // Value between 0 - 100 in percent 
               cookie: FeatureCookieName // Name for the cookie which save the current feature state
               lifetime: 3600 // Lifetime of cookie
```

**Comment by migo315** [comment]
Another idea: Maybe use the `constraint` parameter and extend it with new functions.

Example:
```
best_it_feature_toggle:
    features:      
        feature_123:
            active: true
            
        feature_abc:
            constraints:
                - percentage(50, 'FeatureCookieName', 3600)

        feature_def:
            constraints:
                - ip_address('203.0.113.195', '192.*.*.*')
```

This would be simple, flexibel and do not overload the config. And the user can add own functions if the default functions of this bundle aren't enough.

@Haehnchen What do you think or do you have another idea?
