### ISSUE TITLE
Add correct env handling

### ISSUE THREAD

**Issue by migo315** [bestit/feature-toggle-bundle#14]
`env` variables are resolved at runtime. In TreeBuilder and the DependencyInjection Extension we only have the hash value. As far as I read this is by design and will not change.

We have to add a possibility to set the feature active state via `env` variables.

See PR https://github.com/bestit/feature-toggle-bundle/pull/12 for history.

**Comment by migo315** [comment]
@RedactedProfile 

Symfony 3.4 seems to solve your problem ( https://symfony.com/blog/new-in-symfony-3-4-advanced-environment-variables ) with the `resolve` operator.

> The resolve: operator replaces container parameter names by their values:
> ```
> parameters:
>    project_dir: '/foo/bar'
>    env(DB): 'sqlite://%%project_dir%%/var/data.db'
>    db_dsn: '%env(resolve:DB)%'
> ```

This seems to be exactly what you need. Your example must look something like this:
```
parameters:
   feature_enabled: true 
   env(FEATURE_ENABLED): true 

best_it_feature_toggle:
    features:
       feature_910:
           active: "%env(bool:resolve:FEATURE_ENABLED)%"
```

But I haven't test it yet.
