### ISSUE TITLE
Merge cookie with config stash

### ISSUE THREAD

**Issue by migo315** [bestit/feature-toggle-bundle#18]
So you can separate which feature are active for cookies. Example:

```
best_it_feature_toggle:
    features:      
        feature_123:
            active: true
            cookie: false // Default value - disallow this feature for cookie handling
            
        feature_abc:
            active: false
            cookie: true // Allow this feature for cookie handling
```
